# Generated by Django 6.0.1 on 2026-01-09 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='Unidad')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('product', models.CharField(max_length=100, verbose_name='Producto')),
                ('category', models.CharField(max_length=50, verbose_name='Categoría')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingresos')),
                ('region', models.CharField(max_length=50, verbose_name='Región')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dato de Venta',
                'verbose_name_plural': 'Datos de Ventas',
                'ordering': ['-date'],
            },
        ),
    ]
